---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zmq-server
  namespace: default
  labels:
    app: zmq-server
spec:
  selector:
    matchLabels:
      app: zmq-server
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: app
      labels:
        app: zmq-server
    spec:
      containers:
        - name: app
          image: ghcr.io/cpressland/linkerd_zmq:latest
          args:
            - server
          ports:
            - containerPort: 5555
              name: zmq
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
      serviceAccountName: zmq-server
