---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: zmq-server
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: zmq-server
  port: zmq
  proxyProtocol: unknown
