---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  namespace: default
  name: zmq-server
spec:
  server:
    name: zmq-server
  client:
    meshTLS:
      serviceAccounts:
        - name: zmq-client
